version: "3.8"

include:
  - ../../suave-geth.yml

services:
  suapp-mevm-confidential-store:
    image: suapp:local
    build:
      context: ../..
      dockerfile: Dockerfile
    #volumes:
    #  - ../../framework:/usr/src/suapp-examples/framework
    command: go run examples/mevm-confidential-store/main.go
    depends_on:
      - suave-mevm
