version: "3.8"

include:
  - ../../suave-geth.yml

services:
  suapp-remote-attestation-verification:
    image: suapp:local
    build:
      context: ../..
      dockerfile: Dockerfile
    volumes:
      - ../../framework:/usr/src/suapp-examples/framework
      - ./main.go:/usr/src/suapp-examples/examples/remote-attestation-verification/main.go
    command: go run examples/remote-attestation-verification/main.go
    depends_on:
      - suave-mevm
