version: "3.8"

include:
  - ../../suave-geth.yml

services:
  suapp-onchain-callback:
    image: suapp:local
    build:
      context: ../..
      dockerfile: Dockerfile
    volumes:
      - ../../framework:/usr/src/suapp-examples/framework
    command: go run examples/onchain-callback/main.go
    depends_on:
      - suave-mevm
